# Generated by Django 3.2.16 on 2023-01-12 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('delivery_date', models.DateField(default=datetime.date(2023, 1, 12))),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('production_date', models.DateField(default=datetime.date(2023, 1, 12))),
                ('quantity', models.IntegerField()),
                ('wastage', models.BooleanField(default=False)),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
    ]
