# Generated by Django 3.2.16 on 2023-01-14 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='batch_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(default=datetime.date(2023, 1, 14)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2023, 1, 14)),
        ),
    ]
