# Generated by Django 3.2.16 on 2023-01-15 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230114_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
